### ISSUE TITLE
Aging pages report triggering failed lookup

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail.org#173]
The aging pages report is not functioning properly. The XLSX option triggers an "internal server error" page and the CSV file is blank when you download it. The logs from my local copy indicate there is a failed lookup for a key for a particular blog post.

Here is the full traceback:

```

Traceback (most recent call last):
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/core/utils.py", line 351, in multigetattr
    current = current[bit]

During handling of the above exception ('Page' object is not subscriptable), another exception occurred:
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/core/utils.py", line 356, in multigetattr
    current = getattr(current, bit)

During handling of the above exception ('Page' object has no attribute 'last_published_by_user'), another exception occurred:
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/core/utils.py", line 362, in multigetattr
    current = current[int(bit)]

During handling of the above exception (invalid literal for int() with base 10: 'last_published_by_user'), another exception occurred:
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/reports/base.py", line 41, in get
    return self.as_spreadsheet(self.object_list, self.request.GET.get("export"))
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/mixins.py", line 259, in as_spreadsheet
    return self.write_xlsx_response(queryset)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/mixins.py", line 241, in write_xlsx_response
    self.write_xlsx(queryset, response)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/mixins.py", line 230, in write_xlsx
    self.write_xlsx_row(worksheet, self.to_row_dict(item), row_number + 1)
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/mixins.py", line 148, in to_row_dict
    row_dict = OrderedDict(
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/admin/views/mixins.py", line 149, in <genexpr>
    (field, multigetattr(item, field)) for field in self.list_export
  File "/home/wagtailio/.local/lib/python3.8/site-packages/wagtail/core/utils.py", line 369, in multigetattr
    raise AttributeError(

Exception Type: AttributeError at /admin/reports/aging-pages/
Exception Value: Failed lookup for key [last_published_by_user] in <Page: Team meeting notes 3rd February>

```

**Comment by thibaudcolas** [comment]
Can confirm this is still the case with the new version of the site.

**Comment by zerolab** [comment]
This is a Wagtail bug - https://github.com/wagtail/wagtail/issues/9520 / https://github.com/wagtail/wagtail/pull/9531

**Comment by zerolab** [comment]
Now fixed

**Comment by aliceni81** [comment]
Why do I still have this error even though I upgrade Wagtail to 4.1.1?

**Comment by zerolab** [comment]
@aliceni81 🤷‍♂️
I suggest discussing this in the #support channel in Wagtail Slack
