### ISSUE TITLE
Can't access Wagtail admin in Docker container due to table error

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail.org#374]
I used the `make` commands to update my environment in Docker and I'm getting the following error when I attempt to access the admin portion of the website. The frontend seems to be working okay and I can click around the website itself. Trying to log in to the admin though triggers this template error.

Looks like this table has popped up elsewhere ([#9974](https://github.com/wagtail/wagtail/pull/9974) and [#7901](https://github.com/wagtail/wagtail/issues/7901)). If there is a conflict between the versions of Django and Wagtail we have on this site, I'm not sure yet why it works fine on production but not in Docker.

Here's the trace:

```
Template error:
In template /venv/lib/python3.10/site-packages/wagtail/admin/templates/wagtailadmin/home/user_pages_in_workflow_moderation.html, error at line 4
   column wagtailcore_workflowstate.page_id does not exist
LINE 1: ..._workflowstate" INNER JOIN "wagtailcore_page" ON ("wagtailco...
                                                             ^

   1 : 
   2 : 
   3 : {% load i18n wagtailadmin_tags %}
   4 :  {% if workflow_states %} 
   5 :     {% trans "Your pages in a workflow" as heading %}
   6 :     {% panel id="pages-in-workflow" heading=heading %}
   7 :         <table class="listing">
   8 :             <col />
   9 :             <col width="30%"/>
   10 :             <col width="15%"/>
   11 :             <thead class="w-sr-only">
   12 :                 <tr>
   13 :                     <th class="title">{% trans "Title" %}</th>
   14 :                     <th>{% trans "Task" %}</th>


Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (column wagtailcore_workflowstate.page_id does not exist
LINE 1: ..._workflowstate" INNER JOIN "wagtailcore_page" ON ("wagtailco...
                                                             ^
) was the direct cause of the following exception:
  File "/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/venv/lib/python3.10/site-packages/wagtail/admin/auth.py", line 197, in overridden_render
    return render()
  File "/venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/venv/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/venv/lib/python3.10/site-packages/wagtail/admin/templatetags/wagtailadmin_tags.py", line 921, in component
    return obj.render_html(context)
  File "/venv/lib/python3.10/site-packages/wagtail/admin/ui/components.py", line 20, in render_html
    return template.render(context_data)
  File "/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 314, in render
    if match:
  File "/venv/lib/python3.10/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/
Exception Value: column wagtailcore_workflowstate.page_id does not exist
LINE 1: ..._workflowstate" INNER JOIN "wagtailcore_page" ON ("wagtailco...
```

**Comment by laymonage** [comment]
It looks like the migrations from Wagtail 4.2 has been run (`wagtailcore_workflowstate.page_id does not exist` as the column has been changed into a generic `object_id` in 4.2), but the Wagtail version in the container is still 4.1 (hence it still looks for `page_id`).

Did you perhaps pull the latest production data from Heroku, but have not upgraded the Python dependencies in the container? I'm not sure what the process for the latter is, you might be able to re-run `pip install` (after pulling the latest `main`), but I'm not sure. I think rebuilding the container from the latest `main` branch surely should work, though.

**Comment by vossisboss** [comment]
Yeah. It was a git error on my end it turns out. The dependency file wasn't being pulled in. I think I've got it reset and fixed now so I'm closing this out.
